add nginx Dockerfile
Drunken-Developer-On-Space/docker-files pull request #13
Opened 2021-01-31 07:36 UTC by tunerprime

궁금한 것
1. 왜 nginx 를 foreground 모드 ( daemon이 아닌 상태로 ) 띄워야 할까
2. CMD, ENTRYPOINT 둘 중에 어떤 상황에 어떤걸 써야 더 알맞은 상황인 것인가

resolve #1

2021-01-31 08:43 UTC, davkim1030 requested changes
Openssl로 사설 인증서를 만들어서 https 처리도 부탁드립니다

2021-02-05 13:57 UTC, unyoi commented
@tunerprime 
궁금증 1번은 detach mode 상태에서 컨테이너 내부 프로세스를 background (service , nohup, daemon 등) 으로 기동 했을 때 container가 중지되게 설계되어 있다넹

[https://docs.docker.com/engine/reference/run/#detached--d](url)
Do not pass a service x start command to a detached container. For example, this command attempts to start the nginx service.

$ docker run -d -p 80:80 my_image service nginx start

This succeeds in starting the nginx service inside the container. However, it fails the detached container paradigm in that, the root process (service nginx start) returns and the detached container stops as designed. As a result, the nginx service is started but could not be used. Instead, to start a process such as the nginx web server do the following:

$ docker run -d -p 80:80 my_image nginx -g 'daemon off;'

2021-02-05 15:14 UTC, tunerprime commented
> Openssl로 사설 인증서를 만들어서 https 처리도 부탁드립니다

작업했음 질문 안받음
============================
# curl https://127.0.0.1 -k
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Hi</title>
</head>
<body>
<p>this is test page</p>
</body>
</html>

2021-02-06 07:21 UTC, Dry8r3aD requested changes
please check my review below :)

2021-02-06 07:21 UTC, Dry8r3aD commented on nginx/Dockerfile
> +    && whoami \
please remove debugging log

2021-02-06 07:22 UTC, unyoi requested changes
nginx pid가 /run/nginx dir에 들어간다는 부분 코멘트 남겨주면 좋을 것 같아여~
아니면 nginx pid path를 config 내에서 바꾸던지여

2021-02-06 07:22 UTC, unyoiii commented on nginx/Dockerfile
> +    && mkdir -p /run/nginx
/run/nginx dir를 만드는 이유가 무엇이지용

2021-02-06 07:25 UTC, tunerprime commented on nginx/Dockerfile
> +    && mkdir -p /run/nginx
pid 저장!

2021-02-06 07:57 UTC, Dry8r3aD approved these changes

2021-02-06 08:17 UTC, tunerprime commented
Layer 하나 만드는데 보통 0.5s 차이가 나오기때문에 `가능하면 같은 서비스들끼리 RUN을 돌려 레이어를 만들어 주는게 이득`

2021-02-06 08:18 UTC, unyoi approved these changes
승인합니다 'ㅁ'

2021-02-06 08:18 UTC, merged